[package]
name = "falling_sand"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.13.1"
bytemuck = "1.25.2"
egui = "0.34.2"
egui-wgpu = "0.34.2"
egui-winit = "0.34.2"
i_triangle = "0.46.0"
pixels = "0.17.2"
rand = "0.10.2"
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
strum = "0.28.0"
strum_macros = "0.28.0"
winit = "0.30.13"

sand_render = {path="../sand_render"}